### ISSUE TITLE
'SwiftyPing' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by vsevolod-volkov** [samiyr/SwiftyPing#12]
All SwiftyPing.inits use default protection level resulting them to be internals.
Please explicitly declare SwiftyPing initializers as public to allow other packages to access them.

**Comment by samiyr** [comment]
Should be fixed, see latest commit [1ff9ce6](https://github.com/samiyr/SwiftyPing/commit/1ff9ce641a4cca29c43ceb85ea08f29045fc84c4).
