### ISSUE TITLE
Multiple simultaneous pings are not working.

### ISSUE THREAD

**Issue by vsevolod-volkov** [samiyr/SwiftyPing#13]
When multiple ping sessions simultaneously established, every SwiftyPing instance receives responses from every of parallel pings resulting PingError.identifierMismatch responses. I noticed that behaviour with as many as 37 SwiftyPings in action.
To fix that need to check that distinct response source address in IP header matches SwiftyPing.destination and only then to throw that exceptoin.

**Comment by samiyr** [comment]
I can only reproduce this issue when I use multiple pingers with the same destination. When the destinations are distinct, everything seems to be working as expected. Are you pinging unique addresses or are there duplicates? If there are duplicates, can you elaborate on the use case for this? I can't think of one where you'd need to ping the same target from multiple instances. If all the addresses are unique, can you share some details on your setup so I could try and reproduce this.

**Comment by morithil** [comment]
I am also experiencing this issue when pinging different IP addresses on the local network (i.e. 192.168.1.20 & 192.168.1.21)

**Comment by morithil** [comment]
@vsevolod-volkov did you find a workaround for this?

**Comment by morithil** [comment]
@samiyr  See here my console log for pinging 3 IP addresses in an array using a for loop and the basic pingOnce example script. Note that only 192.168.19 and 192.168.28 are actually connected to the network, .18 is offline.

Pinging camera at: 192.168.1.19...
Pinging camera at: 192.168.1.28...
Pinging camera at: 192.168.1.18...

PingResponse(identifier: 60356, ipAddress: Optional("192.168.1.19"), sequenceNumber: 0, duration: 0.010219931602478027, error: nil)

PingResponse(identifier: 23090, ipAddress: Optional("192.168.1.28"), sequenceNumber: 0, duration: 0.010067939758300781, error: Optional(Edge_Companion.PingError.identifierMismatch(received: 50411, expected: 23090)))

PingResponse(identifier: 17692, ipAddress: Optional("192.168.1.18"), sequenceNumber: 0, duration: 0.009837985038757324, error: Optional(Edge_Companion.PingError.identifierMismatch(received: 50411, expected: 17692)))

**Comment by vsevolod-volkov** [comment]
> @vsevolod-volkov did you find a workaround for this?

Yes, I do. I establish single (non-repeatable) pings, then re-send ping upon response receive.

**Comment by taqiraza** [comment]
> > @vsevolod-volkov did you find a workaround for this?
> 
> Yes, I do. I establish single (non-repeatable) pings, then re-send ping upon response receive.

I am also experiencing same issue when establishing multiple pings simultaneously for different IPs. Only workaround for this to wait for a response then calculate next IP's ping.

**Comment by samiyr** [comment]
It seems that when the kernel receives an ICMP echo response, it cannot decide which socket sent the request, so it just calls every socket callback. I've changed the package payload to be a fingerprint (UUID) which allows differentiating between different callbacks. It now checks this fingerprint and fails silently if they're not the same, indicating that the callback is handling a response from the wrong socket. In my testing this fixes the problem, but let me know if you're still experiencing issues.
