### ISSUE TITLE
Can we ping IP adress more than one ? I am pinging multiple IP adresses. I need to ping every IP twice 

### ISSUE THREAD

**Issue by bcsezer** [samiyr/SwiftyPing#17]

**Comment by krispis1** [comment]
Here's what worked for me (it's pinging every IP once, but can be easily modified with .targetCount):

`func ping(index: Int) {
        let once = try? SwiftyPing(host: "192.168.1.\(index)", configuration: PingConfiguration(interval: 0.5, with: 5), queue: DispatchQueue.global())
        once?.observer = { (response) in
            if response.ipHeader == nil {
                print("not reachable \(response.ipAddress)")
                once?.stopPinging()
                if index+1 <= 254 {
                    self.ping(index: index+1)
                }
            } else {
                print(response.ipAddress)
                once?.stopPinging()
                if index+1 <= 254 {
                    self.ping(index: index+1)
                }
            }
        }
        once?.targetCount = 1
        try? once?.startPinging()
    }`

**Comment by bcsezer** [comment]
Thank you for your response. So for example, you ping 192.168.1.1 twice and then you switch to 192.168.1.2 and ping it twice and this continues until 192.168.1.254.

**Comment by krispis1** [comment]
Yes, this code needs some modification to work for two-time pinging.

**Comment by bcsezer** [comment]
Is it working once? .target Count = 1 in your code?

**Comment by krispis1** [comment]
If you remove both of the `once?.stopPinging()` lines, the pinging will work fine if the target IP is not responding (times out), but the tricky part that i still can't figure out is when the IP returns a valid response. It seems that everything breaks. I've set up a "working" solution for myself that fits my needs so far, but it's messy and I wouldn't recommend for anyone to do the same thing.

**Comment by krispis1** [comment]
It's because i use multithreading, the pinging backend isn't suited for that as far as im conserned.

**Comment by krispis1** [comment]
Another solution is using this. It will ping the current ip as many times as you set it, and then resursively call the ping function again.

```
if response.sequenceNumber == (pinger?.targetCount)!-1 {
         ping()
}
```

**Comment by bcsezer** [comment]
`func startPing() {


         var count = 0
         do {
             ping = try SwiftyPing(host: ipAdresses[count], configuration: PingConfiguration(interval: 0.4, with: 1), queue: DispatchQueue.global())
                ping?.observer = { (response) in
                    DispatchQueue.main.async {
 //                       var message = "\(response.duration! * 1000) ms"
                     var message = "Reachable"
                        if let error = response.error {

                            if error == .responseTimeout {
                                message = "Unreachable"
                            } else if error == .hostNotFound {
                                print(error)
                                message = "Unreachable"
                            }else{
                             message = "Unreachable"
                            }
                        }

                     if count == 254{
                         self.ping?.stopPinging()
                     }else{
                         print(self.ipAdresses[count])
                         let results = IpAdressModal(address: self.ipAdresses[count], success: message)
                         self.ipAdresModalArray.append(results)
                            print(message)
                         count += 1


                     }
                     self.tableView.reloadData()
                    }
                }
 //              ping?.targetCount =
                try ping?.startPinging()
            } catch {
                print(error.localizedDescription)
            }

     }`

**Comment by bcsezer** [comment]
This is my code in my code targetCount works fine but ip adresses all returns Reachable so I try your code and its working fine. I am newbie developer so thank you for your help

**Comment by samiyr** [comment]
Thanks for @krispis1 helping out. I've also added a new property `currentCount` to the pinging instance which gives the current ping count (0 = first ping, 1 = second ping, ...) that might be useful when determining whether to continue pinging.
