### ISSUE TITLE
[help wanted] Concurrent pinging fails when one of the IP addresses return a valid response.

### ISSUE THREAD

**Issue by krispis1** [samiyr/SwiftyPing#18]
While pinging multiple IP's at once with no reach and timeout, it works as expected, but once an IP address is reachable, the concurrency starts to behave unexpectedly.

Here's what i'm working with:

```
class IpPinger {
    
    func ping(index: Int) {
        let once = try? SwiftyPing(host: "192.168.1.\(index)", configuration: PingConfiguration(interval: 0.5, with: 5), queue: DispatchQueue.global())
        once?.observer = { (response) in
            if response.ipHeader == nil {
                print("not reachable \(response.ipAddress)")
                once?.haltPinging()
                if index+10 <= 254 {
                    self.ping(index: index+10)
                }
            } else {
                print(response.ipAddress)
                once?.haltPinging()
                if index+10 <= 254 {
                    self.ping(index: index+10)
                }
            }
        }
        once?.targetCount = 1
        try? once?.startPinging()
    }
    
    func concurrentPing() {
        DispatchQueue.concurrentPerform(iterations: 10, execute: { index in
            self.ping(index: index+1)
        })
    }
    
}
```

**Comment by krispis1** [comment]
<img width="304" alt="Screenshot 2020-11-17 at 00 31 42" src="https://user-images.githubusercontent.com/51785504/99316058-599d6b80-286c-11eb-86d1-279a9c67b32c.png">

Here you can see that 10 parallel operations are being handled, but when the IP returns something, everything breaks and only one operation proceeds.

**Comment by Brolivar** [comment]
Hey! Did you manage to solve this? I'm starting to think the problem is on the library's end. Maybe it doesn't support multithreading well.

I have tried many swift libraries for ip pinging already, and every and each of them have some kind of problem/inconsistency when using them for multithreading...

**Comment by samiyr** [comment]
@Brolivar I'm pretty sure the problem is at the library's end. I haven't had the time to find a solution to this, but I was able to reproduce it at least. I think the problem is that most libraries (at least the ones I've seen) are based on Apple's ping sample code (`SimplePing`), which is based on low-level sockets. These sockets don't behave particularly nice with multithreading. I've been hoping for the `Network` framework to start supporting ICMP, but that hasn't happened yet, so the only way I'm aware of is to use sockets. I hope to have more time in a few weeks to really look into this.

**Comment by Brolivar** [comment]
@samiyr Thank you for the answer. 

Makes sense since all libraries that I used are based on that Apple Module. 

I'll try to (hopefully) find a library that is not based on it, or worst case just make my own workaround.

**Comment by samiyr** [comment]
I'm going to push a new version, which in my preliminary testing seems to fix the erratic behavior. For completeness, this is the code I used (with v. 1.1.8):

```swift
    func batchPing(_ delta: Int = 0) {
        let group = DispatchGroup()
        
        for i in 0..<10 {
            group.enter()
            let once = try? SwiftyPing(host: "10.0.1.\(i + delta)", configuration: PingConfiguration(interval: 0.5, with: 5), queue: DispatchQueue.global())
            once?.observer = { (response) in
                if response.ipHeader == nil {
                    print("not reachable \(response.ipAddress!)")
                    once?.haltPinging()
                } else {
                    print("reachable \(response.ipAddress!)")
                    once?.haltPinging()
                }
                group.leave()
            }
            once?.targetCount = 1
            try? once?.startPinging()
        }
        
        group.notify(queue: .main) {
            if delta + 20 < 254 {
                self.batchPing(delta + 10)
            }
        }

    }

```

Let me know if this fixes the problem.

**Comment by Brolivar** [comment]
@samiyr It fixes it!! After finding a reachable address, now there is a really slight processing time (almost non noticeable) and then it keeps looping through the rest of the addresses. In my opinion works perfect.

I haven't find any weird behaviour in all the tests I have made. If I find something I will let you know!

Thank you pal 👍

**Comment by krispis1** [comment]
Thanks for looking into the issue!
