### ISSUE TITLE
Ping to a non-exist IP, it will get a requestError and the intervals will get faster and faster.

### ISSUE THREAD

**Issue by zuvola** [samiyr/SwiftyPing#19]
Here is the code I tried. 
192.168.3.45 does not exist.
```Swift
let pinger = try? SwiftyPing(host: "192.168.3.45", configuration: PingConfiguration(interval: 1, with: 2), queue: DispatchQueue.global())
pinger?.observer = { (response) in
  print("\(response.sequenceNumber):\(response.duration!):\(response.error!)")
}
try? pinger?.startPinging()
```

The result is like this.
![cap](https://user-images.githubusercontent.com/1144427/101450860-8d047f00-396e-11eb-8723-368bc274b853.gif)

**Comment by samiyr** [comment]
I'm unable to reproduce this, all I see is a steady stream of `responseTimeout`. It this code called from the main thread? The `requestError` is only thrown when the `CFSocketSendData` fails, so there's something odd going on there.

**Comment by zuvola** [comment]
I did it in the main thread. I also tried it on both iOS and Mac and got the same result.
Probably something is wrong with my network...
Thank you.
