### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by Higher08** [samiyr/SwiftyPing#24]
Do you have any plans to support Mac OS?
I have a project for mac, and I really need pinging
Now if I try to use this I got an error SwiftyPing.PingError.invalidLength(received: 0) and it ignoring time interval, but in Ios it working perfectly

**Comment by samiyr** [comment]
It works fine for me on Mac. The `SwiftyPingTest` project now includes a Mac version, give it a try and let me know whether it works on your machine. Note that the Mac app has to have the incoming and outgoing network entitlements enabled.

**Comment by Higher08** [comment]
It was my mistake, my project cant use incoming connections. I enabled and it works fine. Thanks for the answer)
