### ISSUE TITLE
Memory Leak - Ping Configuration

### ISSUE THREAD

**Issue by Daniel-Higgott** [samiyr/SwiftyPing#27]
I am experiencing a memory leak related to the PingConfiguration struct. I am following the example in the Read-Me, sending a single ping, but after every ping, the PingConfiguration is not deallocated. Could be something I am doing wrong, but I think I am just following the basic example...

**Comment by MikesTooLz** [comment]
If I ping and address lets say 3 times, and then I go to the "View Memory Graph Hierarchy" I see at the top "SocketInfo(3)".

So no matter how many times I ping an address, SocketInfo shows that many items in it. Looks like the sockets are being created but not removed after the ping completes.

**Comment by Daniel-Higgott** [comment]
Please see my Pull Request, which contains a fix

**Comment by samiyr** [comment]
This should be fixed in v1.1.14
