### ISSUE TITLE
Timeout not working?

### ISSUE THREAD

**Issue by blackTay** [samiyr/SwiftyPing#9]
While this seems to be the best code around to send plain ICMP pings efficiently on iOS, I have a problem with the timeout. 

I tried to set the timeout to 1s:

```
let once = SwiftyPing(host: "1.1.1.1", configuration: PingConfiguration(interval: 1,with: 1), queue: DispatchQueue.global())
        once?.observer = { (_, response) in
            let duration = response.duration
            print(duration)
            once?.stop()
            print("stopped")
        }
        once?.start()
```

However, I don't get a timeout. If there is e.g. a 2s latency, the observer just normally gets called after 2s printing the latency.
How can I get a real timeout, i.e. that my function above or another one gets called on timeout?

Note: I used the fix in #7 to have just a single ping.

**Comment by pfliegster** [comment]
Same issue for me: timeout doesn't seem to have an effect ... I tried testing it with a local IP address I know doesn't exist & it never enters the .observer closure, or into .errorClosure. Perhaps there is another way I'm able to detect a timeout error (specific throw, error?).

**Comment by samiyr** [comment]
It turned out that the socket timeout error previously implemented was actually just about sending the request, not about receiving it. I have now added a timeout watchdog, so it should now work properly. My testing was limited, so feel free to open a new issue if it still doesn't work.

**Comment by blackTay** [comment]
It now works perfectly. 
This library is the best low level ping library for swift - thank you very much @samiyr for your great work!
